SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM (BOOK AS B INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID) INNER JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY B.AUTHOR_ID, CATEGORY
ORDER BY B.AUTHOR_ID, CATEGORY DESC;