# 서울에 위치 / 평균 점수는 소수점 세 번쨰 자리에서 반올림 / 평균점수를 기준으로 내림차순, 즐겨찾기 기준으로 내림차순

SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS I INNER JOIN REST_REVIEW AS R ON I.REST_ID = R.REST_ID
WHERE ADDRESS LIKE "서울%"
GROUP BY I.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;